export const GET_TODO_LIST = 'GET_TODO_LIST'
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST'
export const TOGGLE_TODO_STATE = 'TOGGLE_TODO_STATE'
export const DISPLAY_INPUT_FILED = 'DISPLAY_INPUT_FILED'
export const DISPLAY_ADD_TODO_FORM = 'DISPLAY_ADD_TODO_FORM'
export const EDIT_TODO='EDIT_TODO';